### PR TITLE
SDK upgrade

### PR DESCRIPTION
**Pull request by danbjoseph**

### CODE REVIEW

**Comment by danbjoseph** [comment]
`app/example.properties` is removed?

**Comment by azzits** [comment]
Will put it back. I renamed the file and it is gone.

**Comment by danbjoseph** [comment]
thanks for continuing to work on this!

**Comment by danbjoseph** [comment]
tested on device and seems good to go. thanks!

@azzits please take a look at https://github.com/AmericanRedCross/dmssdk-android-framework when you have a chance. then we can merge and update the app on the play store. maybe you can walk me through the correct process. i did it once before, and it worked in the end, but i think i messed up the track system.

**Pull request merged**
